version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused
    - errcheck
    - staticcheck
    - misspell
    - nilerr

linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
