package sight

import "regexp"

// goSecurityRules returns built-in static analysis rules for Go security.
func goSecurityRules() []StaticRule {
	return []StaticRule{
		// =====================================================================
		// SECURITY - Go
		// =====================================================================
		{
			ID:          "SEC-GO-001",
			Name:        "SQL Injection",
			Description: "String formatting used in SQL query construction; use parameterized queries instead",
			Language:    "go",
			Pattern:     regexp.MustCompile(`fmt\.Sprintf\s*\(\s*"[^"]*(?:SELECT|INSERT|UPDATE|DELETE|DROP)[^"]*%[sv]`),
			Antipattern: nil,
			Severity:    "critical",
			Category:    "security",
			CWE:         "CWE-89",
			Fix:         "Use parameterized queries with ? or $1 placeholders instead of fmt.Sprintf for SQL",
		},
		{
			ID:          "SEC-GO-002",
			Name:        "Command Injection",
			Description: "Potentially unsanitized input passed to exec.Command",
			Language:    "go",
			Pattern:     regexp.MustCompile(`exec\.Command\s*\([^"` + "`" + `][^,)]*\)`),
			Antipattern: regexp.MustCompile(`exec\.Command\s*\(\s*"[^"]+"\s*\)`),
			Severity:    "critical",
			Category:    "security",
			CWE:         "CWE-78",
			Fix:         "Validate and sanitize all input passed to exec.Command; use an allowlist of permitted commands",
		},
		{
			ID:          "SEC-GO-003",
			Name:        "Path Traversal",
			Description: "User-controlled path used in file operations without filepath.Clean or validation",
			Language:    "go",
			Pattern:     regexp.MustCompile(`(?:os\.(?:Open|ReadFile|Create|WriteFile)|filepath\.Join)\s*\(.*(?:req\.|r\.|input|param|query|user)`),
			Antipattern: regexp.MustCompile(`filepath\.Clean`),
			Severity:    "high",
			Category:    "security",
			CWE:         "CWE-22",
			Fix:         "Use filepath.Clean() and validate the resolved path is within the expected directory",
		},
		{
			ID:          "SEC-GO-004",
			Name:        "Hardcoded Secret",
			Description: "Hardcoded password or secret string detected",
			Language:    "go",
			Pattern:     regexp.MustCompile(`(?i)(?:password|secret|api_?key|token|private_?key)\s*(?::?=|=)\s*"[^"]{4,}`),
			Antipattern: regexp.MustCompile(`(?i)(?:test|example|placeholder|TODO|CHANGE|xxx|dummy)`),
			Severity:    "critical",
			Category:    "security",
			CWE:         "CWE-798",
			Fix:         "Use environment variables or a secrets manager instead of hardcoded credentials",
		},
		{
			ID:          "SEC-GO-005",
			Name:        "Insecure TLS",
			Description: "TLS certificate verification is disabled",
			Language:    "go",
			Pattern:     regexp.MustCompile(`InsecureSkipVerify\s*:\s*true`),
			Antipattern: nil,
			Severity:    "high",
			Category:    "security",
			CWE:         "CWE-295",
			Fix:         "Remove InsecureSkipVerify: true; configure proper TLS certificate validation",
		},
		{
			ID:          "SEC-GO-006",
			Name:        "Weak Crypto (MD5)",
			Description: "MD5 is cryptographically broken and should not be used for security purposes",
			Language:    "go",
			Pattern:     regexp.MustCompile(`md5\.(?:New|Sum)`),
			Antipattern: regexp.MustCompile(`(?i)(?:checksum|fingerprint|cache|etag|non.?security)`),
			Severity:    "medium",
			Category:    "security",
			CWE:         "CWE-328",
			Fix:         "Use crypto/sha256 or crypto/sha512 instead of MD5 for security-sensitive operations",
		},
		{
			ID:          "SEC-GO-007",
			Name:        "Weak Crypto (SHA1)",
			Description: "SHA-1 is deprecated for security use; collisions are practical",
			Language:    "go",
			Pattern:     regexp.MustCompile(`sha1\.(?:New|Sum)`),
			Antipattern: regexp.MustCompile(`(?i)(?:git|fingerprint|cache|etag|non.?security)`),
			Severity:    "medium",
			Category:    "security",
			CWE:         "CWE-328",
			Fix:         "Use crypto/sha256 or crypto/sha512 instead of SHA-1 for security-sensitive operations",
		},
		{
			ID:          "SEC-GO-008",
			Name:        "Unvalidated Redirect",
			Description: "HTTP redirect using user-controlled input without validation",
			Language:    "go",
			Pattern:     regexp.MustCompile(`http\.Redirect\s*\(.*(?:r\.(?:URL|Form|Query)|req\.|param|input)`),
			Antipattern: nil,
			Severity:    "medium",
			Category:    "security",
			CWE:         "CWE-601",
			Fix:         "Validate redirect URLs against an allowlist of permitted destinations",
		},
		{
			ID:          "SEC-GO-009",
			Name:        "Sensitive Data in Log",
			Description: "Potentially logging sensitive data (passwords, tokens, secrets)",
			Language:    "go",
			Pattern:     regexp.MustCompile(`(?:log\.|slog\.|logger\.)(?:Print|Info|Debug|Warn|Error|Fatal).*(?i)(?:password|token|secret|key|credential)`),
			Antipattern: regexp.MustCompile(`(?i)(?:redact|mask|\*\*\*|<hidden>)`),
			Severity:    "medium",
			Category:    "security",
			CWE:         "CWE-532",
			Fix:         "Redact sensitive values before logging; never log passwords, tokens, or API keys",
		},
		{
			ID:          "SEC-GO-010",
			Name:        "Defer in Loop",
			Description: "defer inside a loop can accumulate resources until the function returns",
			Language:    "go",
			Pattern:     regexp.MustCompile(`^\s*defer\s+`),
			Antipattern: nil,
			Severity:    "medium",
			Category:    "correctness",
			CWE:         "",
			Fix:         "Move the deferred call into a helper function or handle resource cleanup explicitly in the loop",
		},
	}
}

// goCorrectnessRules returns built-in correctness rules for Go.
func goCorrectnessRules() []StaticRule {
	return []StaticRule{
		// =====================================================================
		// CORRECTNESS - Go
		// =====================================================================
		{
			ID:          "COR-GO-001",
			Name:        "Unchecked Error",
			Description: "Function return value that likely includes an error is discarded",
			Language:    "go",
			Pattern:     regexp.MustCompile(`^\s*[a-zA-Z_][a-zA-Z0-9_.]*\s*\(.*\)\s*$`),
			Antipattern: regexp.MustCompile(`(?:^//|^\s*//|defer|go\s+|fmt\.Print|log\.|println|print\()`),
			Severity:    "medium",
			Category:    "correctness",
			CWE:         "CWE-252",
			Fix:         "Capture and handle the returned error: if err != nil { return err }",
		},
		{
			ID:          "COR-GO-002",
			Name:        "Goroutine Leak Risk",
			Description: "Goroutine launched without visible context cancellation or done channel",
			Language:    "go",
			Pattern:     regexp.MustCompile(`\bgo\s+func\s*\(`),
			Antipattern: regexp.MustCompile(`(?:ctx|context|done|cancel|Done\(\)|quit|stop|timer|ticker)`),
			Severity:    "medium",
			Category:    "correctness",
			CWE:         "",
			Fix:         "Pass a context.Context or done channel to goroutines to enable graceful shutdown",
		},
		{
			ID:          "COR-GO-003",
			Name:        "Race Condition Risk",
			Description: "Shared variable access in goroutine without synchronization",
			Language:    "go",
			Pattern:     regexp.MustCompile(`go\s+func\s*\([^)]*\)\s*\{[^}]*(?:[a-z]+\s*(?:\+\+|--|(?:\+|-|\*|/)=))`),
			Antipattern: regexp.MustCompile(`(?:mutex|Mutex|sync\.|atomic\.|Lock\(\)|chan\s)`),
			Severity:    "high",
			Category:    "correctness",
			CWE:         "CWE-362",
			Fix:         "Use sync.Mutex, sync/atomic, or channels to synchronize shared state access",
		},
		{
			ID:          "COR-GO-004",
			Name:        "nil Map Write",
			Description: "Writing to a potentially nil map causes a runtime panic",
			Language:    "go",
			Pattern:     regexp.MustCompile(`var\s+\w+\s+map\[`),
			Antipattern: regexp.MustCompile(`=\s*(?:make|map\[)`),
			Severity:    "high",
			Category:    "correctness",
			CWE:         "",
			Fix:         "Initialize the map with make() before writing to it",
		},
	}
}
